In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

Maak een Jupyter Notebook waarin je het tabje “AmesHousing” van het bestand AmesHousing.xlsx inleest, als DataFrame in Python. Zorg ervoor dat elke Excel-kolom overeenkomt met een DataFrame-kolom.

In [148]:
df = pd.read_excel("AmesHousing.xlsx")
df

,ID,SalePrice,Garage,Overall Qual,Gr Liv Area,Total Bsmt SF,Lot Area,Year Built,Full Bath,Bedroom AbvGr,Neighborhood,House Style
0,1,215000,yes,6,1656,1080.0,31770,1960,1,3,NAmes,1Story
1,2,105000,yes,5,896,882.0,11622,1961,1,2,NAmes,1Story
2,3,172000,yes,6,1329,1329.0,14267,1958,1,3,NAmes,1Story
3,4,244000,yes,7,2110,2110.0,11160,1968,2,3,NAmes,1Story
4,5,189900,yes,5,1629,928.0,13830,1997,2,3,Gilbert,2Story
...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,142500,yes,6,1003,1003.0,7937,1984,1,3,Mitchel,SLvl
2926,2927,131000,yes,5,902,864.0,8885,1983,1,2,Mitchel,1Story
2927,2928,132000,no,5,970,912.0,10441,1992,1,3,Mitchel,SFoyer
2928,2929,170000,yes,5,1389,1389.0,10010,1974,1,2,Mitchel,1Story
2929,2930,188000,yes,7,2000,996.0,9627,1993,2,3,Mitchel,2Story

Open AmesHousing.xlsx in Excel en lees de inhoud van het tabje “Data Dictionary” goed door. Deze geeft de betekenis weer van elke feature én van de targetvariabele. Zoek uit in welke kolom de targetvariabele staat en maak een top 3 van features waarvan je verwacht dat die het meest voorspellend zijn voor de targetvariabele. Let op: minstens één van deze features moet categorisch zijn! Noteer de gekozen features en het target in je logboek.

Target: SalePrice
Meest voorspellend: Neighborhood, Year Built en Gr Liv Area

Prepareer je data in je Jupyter Notebook:
One-hot encode je uitgekozen categorische feature(s)

In [149]:
df = df.loc[:, ['SalePrice', 'Gr Liv Area', 'Neighborhood', 'Overall Qual', 'Lot Area', 'House Style']]
# 
df

      SalePrice  Gr Liv Area Neighborhood  Overall Qual  Lot Area House Style
0        215000         1656        NAmes             6     31770      1Story
1        105000          896        NAmes             5     11622      1Story
2        172000         1329        NAmes             6     14267      1Story
3        244000         2110        NAmes             7     11160      1Story
4        189900         1629      Gilbert             5     13830      2Story
...         ...          ...          ...           ...       ...         ...
2925     142500         1003      Mitchel             6      7937        SLvl
2926     131000          902      Mitchel             5      8885      1Story
2927     132000          970      Mitchel             5     10441      SFoyer
2928     170000         1389      Mitchel             5     10010      1Story
2929     188000         2000      Mitchel             7      9627      2Story

[2930 rows x 6 columns]

In [150]:
dummies_dataframe = pd.get_dummies(df.loc[:, ['Neighborhood' , 'House Style']], drop_first=True)
#
dummies_dataframe

,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,Neighborhood_Edwards,Neighborhood_Gilbert,Neighborhood_Greens,Neighborhood_GrnHill,...,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2926,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2927,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2928,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2929,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [151]:
df = pd.concat([df, dummies_dataframe], axis=1)
df = df.drop(['Neighborhood', 'House Style'], axis=1)
#
df

,SalePrice,Gr Liv Area,Overall Qual,Lot Area,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,...,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl
0,215000,1656,6,31770,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,105000,896,5,11622,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2,172000,1329,6,14267,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,244000,2110,7,11160,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,189900,1629,5,13830,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,142500,1003,6,7937,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2926,131000,902,5,8885,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2927,132000,970,5,10441,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2928,170000,1389,5,10010,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2929,188000,2000,7,9627,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

Splits de dataset horizontaal én verticaal, zodat er vier “stukken” ontstaan.

In [152]:
X = df.loc[df['SalePrice'].notna(), :]
X = X.drop('SalePrice', axis=1)
Y = df.loc[df['SalePrice'].notna(), 'SalePrice']

In [153]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size= 0.15,
    random_state=1
)

Initialiseer een lineair regressiemodel in je Jupyter Notebook en train deze op de juiste “stukken” uit stap 4b. Doe hierbij onderzoek naar de zogeheten “hyperparameters” die je bij dit model kan instellen met behulp van de pythonfunctie help(). Kies hierbij voor een willekeurige combinatie van minstens 2 hyperparameters. Noteer deze laatste twee zgn. “hyperparameters” in je logboek.

In [154]:
reg_model = LinearRegression()
reg_model.fit(X_train, Y_train)
y_pred = reg_model.predict(X_test)

In [155]:
print(mean_squared_error(Y_test, y_pred))
print(mean_absolute_error(Y_test, y_pred))
print(reg_model.score(X_test, Y_test))

1033996998.5470557
21723.89695213932
0.8344061157019381